# Generated by Django 4.0.4 on 2022-04-16 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name="Person's first name")),
                ('last_name', models.CharField(max_length=30, verbose_name="Person's last name")),
                ('photo', models.CharField(max_length=100, verbose_name="Person's photo direction")),
                ('age', models.IntegerField(verbose_name="Person's age")),
                ('residence', models.CharField(max_length=100, verbose_name="Person's residence direction")),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name="Person's sex")),
                ('phone', models.CharField(max_length=15, verbose_name="Person's phone")),
                ('idNumber', models.CharField(max_length=10, verbose_name="Person's id")),
                ('isAdmin', models.BooleanField(default=False, verbose_name='Is this Person the admin?')),
                ('isDoctor', models.BooleanField(verbose_name='Is this Person a doctor?')),
                ('isNurse', models.BooleanField(verbose_name='Is this Person a nurse?')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomTemperature', models.FloatField(verbose_name="Room's Temperature")),
                ('patientTemperature', models.FloatField(verbose_name="Patient's Temperature")),
                ('roomHumidity', models.FloatField(verbose_name="Room's relative humidity %")),
                ('roomDustLevel', models.IntegerField(verbose_name="Room's dust level in %")),
                ('roomAirQuality', models.IntegerField(verbose_name="Room's AirQuality in %")),
                ('patientPulse', models.FloatField(verbose_name="Patient's pulse value")),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_nameReference', models.CharField(max_length=15, verbose_name="Reference Person's first name")),
                ('last_nameReference', models.CharField(max_length=15, verbose_name="Reference Person's last name")),
                ('kinshipReference', models.CharField(choices=[('H', 'Esposo'), ('A', 'Amigo'), ('F', 'Familiar')], max_length=1, verbose_name="Reference Person's kinshipness")),
                ('phone_reference', models.CharField(max_length=15, verbose_name="Reference person's phone number")),
                ('bmi', models.FloatField(verbose_name="Person's BMI")),
                ('bloodType', models.CharField(choices=[('O+', 'O Positivo'), ('O-', 'O Negativo'), ('A+', 'A Positivo'), ('A-', 'A Negativo'), ('B+', 'B Positivo'), ('B-', 'B Negativo'), ('AB+', 'AB Positivo'), ('AB-', 'AB Negativo')], max_length=3)),
                ('ars', models.CharField(max_length=15, verbose_name="Person's ARS type")),
                ('join_date', models.DateField(verbose_name="Person's joining date")),
                ('illness', models.CharField(max_length=50, verbose_name="Persons's illness")),
                ('hospitalization', models.CharField(choices=[('U', 'Urgente'), ('P', 'Programado'), ('I', 'Intrahospitalario')], max_length=1, verbose_name="Patient's type of hospitalization")),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor', to='salusApp.person')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='nurse', to='salusApp.person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salusApp.person')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='salusApp.room')),
            ],
        ),
    ]
