# Generated by Django 4.0.4 on 2022-04-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salusApp', '0005_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
