# Generated by Django 4.0.4 on 2022-04-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salusApp', '0009_remove_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='residence',
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(default=None, max_length=100, verbose_name="Person's address"),
            preserve_default=False,
        ),
    ]
