# Generated by Django 4.0.4 on 2022-04-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salusApp', '0010_remove_person_residence_person_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.FileField(upload_to='', verbose_name="Person's photo direction"),
        ),
    ]
