# Generated by Django 4.0.4 on 2022-04-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salusApp', '0011_alter_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(upload_to='salus_images', verbose_name="Person's photo"),
        ),
    ]
