# Generated by Django 4.0.4 on 2022-04-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salusApp', '0013_alter_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='height_in_meters',
            field=models.FloatField(default=None, verbose_name="Perons's Height"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='weight_in_pounds',
            field=models.FloatField(default=None, verbose_name="Perons's Weight"),
            preserve_default=False,
        ),
    ]
