# Generated by Django 4.0.4 on 2022-04-18 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salusApp', '0014_patient_height_in_meters_patient_weight_in_pounds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='patientPulse',
        ),
        migrations.RemoveField(
            model_name='room',
            name='patientTemperature',
        ),
        migrations.RemoveField(
            model_name='room',
            name='roomAirQuality',
        ),
        migrations.RemoveField(
            model_name='room',
            name='roomDustLevel',
        ),
        migrations.RemoveField(
            model_name='room',
            name='roomHumidity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='roomTemperature',
        ),
        migrations.AddField(
            model_name='room',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='roomName',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Sensores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomTemperature', models.FloatField(verbose_name="Room's Temperature")),
                ('patientTemperature', models.FloatField(verbose_name="Patient's Temperature")),
                ('roomHumidity', models.FloatField(verbose_name="Room's relative humidity %")),
                ('roomDustLevel', models.IntegerField(verbose_name="Room's dust level in %")),
                ('roomAirQuality', models.IntegerField(verbose_name="Room's AirQuality in %")),
                ('patientPulse', models.FloatField(verbose_name="Patient's pulse value")),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salusApp.room')),
            ],
        ),
    ]
