# Generated by Django 4.0.4 on 2022-04-18 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salusApp', '0015_remove_room_patientpulse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='person',
        ),
        migrations.AddField(
            model_name='patient',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='salusApp.person'),
            preserve_default=False,
        ),
    ]
