# Generated by Django 4.0.4 on 2022-04-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salusApp', '0016_remove_patient_person_patient_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, upload_to='salusApp/static/media/'),
        ),
    ]
