# Generated by Django 4.0.4 on 2022-04-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salusApp', '0017_alter_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensores',
            name='patientElectro',
            field=models.IntegerField(default=None, verbose_name="Patient's elect"),
            preserve_default=False,
        ),
    ]
