# Generated by Django 3.2.16 on 2022-10-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salusApp', '0019_auto_20221013_1739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sensores',
            new_name='Sensors',
        ),
    ]
