# Generated by Django 4.0.4 on 2022-10-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salusApp', '0020_rename_sensores_sensors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
