# Generated by Django 4.0.4 on 2022-10-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salusApp', '0021_alter_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='uuid',
            field=models.CharField(default=None, max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='uuid',
            field=models.CharField(default=None, max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='uuid',
            field=models.CharField(default=None, max_length=36),
            preserve_default=False,
        ),
    ]
