# Generated by Django 4.0.4 on 2022-10-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salusApp', '0022_patient_uuid_person_uuid_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, default='blank-picture.jpg', null=True, upload_to='images/'),
        ),
    ]
