# Generated by Django 4.0.4 on 2022-10-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salusApp', '0023_alter_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, default='images/blank-picture.jpg', null=True, upload_to='images/'),
        ),
    ]
